apiVersion: v1
kind: Pod
metadata:
  name: ibench-cpu
  namespace: xinan
  labels:
    name: ibench-cpu
spec:
  containers:
    - image: mirrors.tencent.com/cloudns/cloudrepo:cpu
      name: ibench-cpu
      command: ["/bin/sh"]
      args: ["-c", " ./cpu 120"]
  tolerations:
      - effect: NoSchedule
        operator: Exists
  nodeSelector:
    kubernetes.io/hostname: node-100.91.31.242
